### ISSUE TITLE
Few Feature Requests

### ISSUE THREAD

**Issue by nulledone** [SimpleMobileTools/Simple-Music-Player#108]
_- First of all, .OPUS file support._
- Lyrics over Album Art in main application (tap to toggle maybe?, like in Samsung Music app)
- Showing previous button in notifications without expanding (or a option switch to enlarge notification)
- Change Lockscreen wallpaper with Album Art
- Dynamically change notification color based on Album Art (like in VLC)

**Comment by tibbi** [comment]
there is .opus file support, arent you using some too old app version? It has been added a month ago.

**Comment by nulledone** [comment]
Oh sorry, I thought that OPUS files are going to be recognized automatically, but it seems like I have to add them manually. It indeed support OPUS, but seems like hangs on and crashes my device when I choose a folder with few subfolders.

Containing 300~ OPUS files in a total of 70~ folders. 

App becomes unresponsive and crashes constantly when there are more than 30 opus files in directory.

Adding a progression bar might be handy.

**Comment by tibbi** [comment]
opus files are handled a bit differently. At startup Im obviously not browsing through the whole device, I just ask the system for a list of audio files. Opus files apparently dont belong there, so Im not aware of them. You have to manually select a file or folder for adding them. Anyway retest it with version 3.2.1 released a couple hours ago, some crashes have been fixed. Maybe yours too, we will see.

**Comment by nulledone** [comment]
It still hangs , it might be due to reading file tag, but foobar seems to not have this issue.

I can add 7-8 files at a time with 15 seconds of heavy lag.

I can also add them as mp3(not converted, only extension rename) with no problems.

**Comment by tibbi** [comment]
opus should work better already. Also Lockscreen art and a Previous notification button will be added in 4.1.0

**Comment by tibbi** [comment]
actually the VLC-like color changing will be added too as it is done somehow automatically by the system and I couldnt turn it off :p

**Comment by tibbi** [comment]
some things have been fixed already, create a separate report per issue
